=== rafajare/PrimeroDaw/EXAMEN 2 EVALUACION/PEN RAFA/Lenguaje de marcas/alumno.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <!-- ELEMENTOS -->
  
  <xs:element name ="alumno">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="direccion">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="calle" type="xs:string"/>
              <xs:element name="numero" type="xs:string"/>
              <xs:element name="ciudad" type="xs:string"/>
              <xs:element name="provincia" type="xs:string">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="CP" type="xs:integer"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="telefono">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:pattern value="[0-9]{9}"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rafajare/PrimeroDaw/3 EVALUACION/PEN RAFA/Lenguaje de marcas/alumnos.xml
<?xml version="1.0" encoding="utf-8"?>
<alumno dni="111" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="alumno.xsd">
  <nombre>Antonio PÃ©rez</nombre>
  <direccion>
    <calle>Calle Fuente</calle>
    <numero>4</numero>
    <ciudad>Jabugo</ciudad>
    <provincia CP="46460">Huelva</provincia>
  </direccion>
  <telefono>959222324</telefono>
</alumno>
