=== rafajare/PrimeroDaw/3 EVALUACION/PEN RAFA/Lenguaje de marcas/pizzas.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="pizzas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pizza" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ingrediente" type="xs:string" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="nombre" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="nombre" type="xs:string"/>
            <xs:attribute name="precio" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rafajare/PrimeroDaw/EXAMEN 2 EVALUACION/PEN RAFA/Lenguaje de marcas/pizzas.xml
<?xml version="1.0" encoding="UTF-8"?>
<pizzas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pizzas.xsd"> 
<pizza nombre="Barbacoa" precio="8"> 
	<ingrediente nombre="Salsa Barbacoa"/> 
	<ingrediente nombre="Mozzarella"/> 
	<ingrediente nombre="Pollo"/> 
	<ingrediente nombre="Bacon"/> 
	<ingrediente nombre="Ternera"/> 
</pizza> 
<pizza nombre="Margarita" precio="6"> 
	<ingrediente nombre="Tomate"/> 
	<ingrediente nombre="Jamón"/> 
	<ingrediente nombre="Queso"/> 
</pizza> 
<pizza nombre="Tres Quesos" precio="10"> 
	<ingrediente nombre="Cabrales"/> 
	<ingrediente nombre="Mozzarella"/> 
	<ingrediente nombre="Manchego"/> 
	<ingrediente nombre="Jamón"/> 
	<ingrediente nombre="Bacon"/> 
</pizza> 
</pizzas>
