<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE CLASE
[ 

			<!ELEMENT CLASE (INSTITUTO, CURSO, ALUMNOS)>
			<!ELEMENT INSTITUTO (#PCDATA)>
			<!ELEMENT CURSO (#PCDATA)>
			<!ELEMENT ALUMNOS (NOMBRE, APELLIDOS, EDAD, ASIGNATURAS)+>
			<!ELEMENT NOMBRE (#PCDATA)>
			<!ELEMENT APELLIDOS (#PCDATA)>
			<!ELEMENT EDAD (#PCDATA)>
			<!ELEMENT ASIGNATURAS (#PCDATA)>	
]>			


<CLASE>

	<INSTITUTO> IES MANUEL SANCHIS GUARNER </INSTITUTO>
	<CURSO>     2ª BACHILLERATO	 ARTÍSTICO </CURSO>
	
	<ALUMNOS>    
		
		<NOMBRE>    Alicia			</NOMBRE>
		<APELLIDOS> López Villalba	 </APELLIDOS>
		<EDAD>		17				 </EDAD>
		<ASIGNATURAS> dibujo, volumen, castellano, valenciano</ASIGNATURAS>
	
	</ALUMNOS>      
	
</CLASE>			