<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE CD
[
		<!ELEMENT CD (TITULO, INTERPRETE, CANCIONES)>
		<!ELEMENT TITULO (#PCDATA)>
		<!ELEMENT INTERPRETE (#PCDATA)>
		<!ELEMENT CANCIONES (TITULO_CANCION, DURACION, COMPOSITOR)>
		<!ELEMENT TITULO_CANCION (#PCDATA)>
		<!ELEMENT DURACION (#PCDATA)>
		<!ELEMENT COMPOSITOR (#PCDATA)>
]>


<CD>

<TITULO>		TITULO DEL CD				</TITULO>	
<INTERPRETE>           INTERPRETE			</INTERPRETE>
	
	<CANCIONES> 					
		
		<TITULO_CANCION> TITULO DE LA CANCION	</TITULO_CANCION>
		<DURACION>		DURACION DE LA CANCION	</DURACION>
		<COMPOSITOR>	COMPOSITOR DEL CD	    </COMPOSITOR>
	
	</CANCIONES>	

</CD>	
	
